### ISSUE TITLE
Browsersync problem

### ISSUE THREAD

**Issue by OutsourcedGuru** [vguillou/parallax-element#4]
Not that it's necessarily your problem, but the Polymer Starter Kit comes with a pre-installation of Browsersync.  Per the online tutorials it allows you to point many browsers and devices at the same testing link like http://192.168.0.50:5000 and the Browsersync JavaScript gets injected right after the body tag, allowing all these browsers to work in tandem.  If you scroll in one browser, all others scroll similarly.

It looks like something regarding the parallax-element's scrolling behavior is faking out the Browsersync's normal trapping of the scroll function, not sure why.  I can fire up a Safari on the MacBook and then point my iPhone and my iPad at the same external address.  If I click the fullscreen button in one browser, it will change states in the iPad, for example.  So I know that Browsersync appears to be trapping mouse clicks... just not the scrolling feature.

Interestingly, if I do a two-finger scrolling gesture on either the iPad or the iPhone it wants to mimic this behavior on the other portable.  So it suggests that parallax-element is faking out Browsersync for the single-finger scroll gesture.

I don't necessarily expect you to troubleshoot this or to care much.  Just noting the incompatibility.

**Comment by vguillou** [comment]
I'm pretty sure that PSK does not support that as well.
I believe the reason is related to the fact that browser-sync by default synchronize the scroll position of the window.

PSK uses a `paper-scroll-header-panel` to host the scrolling content, so browser-sync would need some more configuration to make it work.

**Comment by OutsourcedGuru** [comment]
Just noting what I'm seeing out here.  Closing this since it's not really a bug.
